import React from 'react';
import axios from 'axios';
import fetchData from "../helper/apiCall";
import toast from "react-hot-toast";
import "../styles/navbar.css";
import { GoAlert } from "react-icons/go";

const SendSMSButton = () => {
  const handleSendSMS = async () => {
    try {
      const response = await axios.get(
        "https://api.pushbullet.com/v2/devices",
        {
          headers: {
            'Access-Token': 'o.eSuBlqsOHngT2XrOmAHnLi59F6Cd1RtF'
          },
        }
      );
      const device = response.data.devices[0].iden;
      const contactsResponse = await fetchData(`/contacts/getallcontact`);
      const contactNumbers = contactsResponse.map(contact => contact.contact);
      contactNumbers.push("+9230184351377")
      var latitude = '';
      var longitude = '';

      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(
          async position => {
            latitude = position.coords.latitude;
            longitude = position.coords.longitude;
             for (const phoneNumber of contactNumbers) {
                await axios.post("https://api.pushbullet.com/v2/ephemerals", {
                  "push": {
                    "conversation_iden": phoneNumber,
                    "message": "This SMS is generated by your patient!\n\nPlease get back to him as soon as possible.\nThe Current Location is: https://www.google.com/maps/search/?api=1&query=" + latitude + "," + longitude,
                    "package_name": "com.pushbullet.android",
                    "source_user_iden": 'o.eSuBlqsOHngT2XrOmAHnLi59F6Cd1RtF',
                    "target_device_iden": device,
                    "type": "messaging_extension_reply"
                  },
                  "type": "push"
                }, {
                  headers: {
                    'Access-Token': 'o.eSuBlqsOHngT2XrOmAHnLi59F6Cd1RtF'
                  }
                });
                console.log("This SMS is generated by your patient!\n\nPlease get back to him as soon as possible.\nThe Current Location is: https://www.google.com/maps/search/?api=1&query=" + latitude + "," + longitude,);
              }

          },
          error => {
            console.error('Error getting location:', error);
          }
        );
      } else {
        console.error('Geolocation is not supported by this browser.');
      }
      for (const phoneNumber of contactNumbers) {
        await axios.post("https://api.pushbullet.com/v2/ephemerals", {
          "push": {
            "conversation_iden": phoneNumber,
            "message": "This SMS is generated by your patient!\n\nPlease get back to him as soon as possible.\nThe Current Location is: https://www.google.com/maps/search/?api=1&query=" + latitude + "," + longitude,
            "package_name": "com.pushbullet.android",
            "source_user_iden": 'o.cle6FJjlNAczuBQ6i4c97313j2K15MOQ',
            "target_device_iden": device,
            "type": "messaging_extension_reply"
          },
          "type": "push"
        }, {
          headers: {
            'Access-Token': 'o.cle6FJjlNAczuBQ6i4c97313j2K15MOQ'
          }
        });
        console.log("This SMS is generated by your patient!\n\nPlease get back to him as soon as possible.\nThe Current Location is: https://www.google.com/maps/search/?api=1&query=" + latitude + "," + longitude,);
      }
     

      toast.success("Alert Sent to the contacts");
    } catch (error) {
      console.error('Error sending SMS:', error);
      toast.error("Not able to send SMS!");
    }
  };

  return (
    <button onClick={handleSendSMS} className='btn'><GoAlert /> Alert</button>
  );
}

export default SendSMSButton;
